import { browserStore, getDatabase } from "./db";
import { preferencesRepository } from "./preferences-repository";
import type { AvailabilityAlert, AvailabilitySnapshot, MediaSummary } from "@/types/media";
const nowIso=()=>new Date().toISOString();
const profileId=async()=>(await preferencesRepository.getPreferences()).activeProfileId;
export const availabilityRepository={
  async listAlerts():Promise<AvailabilityAlert[]>{const profile=await profileId();const db=await getDatabase();if(!db)return browserStore.read().availabilityAlerts.filter((item)=>item.profileId===profile);const rows=await db.select<Array<Record<string,unknown>>>("SELECT * FROM availability_alerts WHERE profile_id=$1 ORDER BY created_at DESC",[profile]);return rows.map((row)=>({id:String(row.id),profileId:String(row.profile_id),mediaId:Number(row.media_id),mediaType:row.media_type==="movie"?"movie":"series",title:String(row.title),region:String(row.region),providerIds:JSON.parse(String(row.provider_ids)),enabled:Boolean(row.enabled),createdAt:String(row.created_at)}));},
  async getAlert(mediaId:number,mediaType:MediaSummary["mediaType"]):Promise<AvailabilityAlert|null>{return (await this.listAlerts()).find((item)=>item.mediaId===mediaId&&item.mediaType===mediaType)??null;},
  async toggle(media:MediaSummary,region:string,providerIds:number[]):Promise<AvailabilityAlert|null>{const existing=await this.getAlert(media.id,media.mediaType);if(existing){await this.remove(existing.id);return null;}const item:AvailabilityAlert={id:crypto.randomUUID(),profileId:await profileId(),mediaId:media.id,mediaType:media.mediaType,title:media.title,region,providerIds,enabled:true,createdAt:nowIso()};const db=await getDatabase();if(!db){const store=browserStore.read();store.availabilityAlerts.push(item);browserStore.write(store);return item;}await db.execute("INSERT INTO availability_alerts (id,profile_id,media_id,media_type,title,region,provider_ids,enabled,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,1,$8)",[item.id,item.profileId,item.mediaId,item.mediaType,item.title,item.region,JSON.stringify(item.providerIds),item.createdAt]);return item;},
  async remove(id:string){const db=await getDatabase();if(!db){const store=browserStore.read();store.availabilityAlerts=store.availabilityAlerts.filter((item)=>item.id!==id);browserStore.write(store);return;}await db.execute("DELETE FROM availability_alerts WHERE id=$1",[id]);},
  async getSnapshot(mediaId:number,mediaType:MediaSummary["mediaType"],region:string):Promise<AvailabilitySnapshot|null>{const db=await getDatabase();if(!db)return browserStore.read().availabilitySnapshots.find((item)=>item.mediaId===mediaId&&item.mediaType===mediaType&&item.region===region)??null;const rows=await db.select<Array<Record<string,unknown>>>("SELECT * FROM availability_snapshots WHERE media_id=$1 AND media_type=$2 AND region=$3",[mediaId,mediaType,region]);const row=rows[0];return row?{mediaId:Number(row.media_id),mediaType:row.media_type==="movie"?"movie":"series",region:String(row.region),providerIds:JSON.parse(String(row.provider_ids)),checkedAt:String(row.checked_at)}:null;},
  async saveSnapshot(snapshot:AvailabilitySnapshot){const db=await getDatabase();if(!db){const store=browserStore.read();store.availabilitySnapshots=store.availabilitySnapshots.filter((item)=>!(item.mediaId===snapshot.mediaId&&item.mediaType===snapshot.mediaType&&item.region===snapshot.region));store.availabilitySnapshots.push(snapshot);browserStore.write(store);return;}await db.execute("INSERT OR REPLACE INTO availability_snapshots (media_id,media_type,region,provider_ids,checked_at) VALUES ($1,$2,$3,$4,$5)",[snapshot.mediaId,snapshot.mediaType,snapshot.region,JSON.stringify(snapshot.providerIds),snapshot.checkedAt]);}
};
